theme: jekyll-theme-minimal
title:  /// iñaki /<br> san&nbsp;pedro //////
description: I&ntilde;aki San Pedro <br> (/i'ɲakɪ 'sam 'peðro/) <br><br> Associate Professor <br> Department of Logic and &nbsp;&nbsp;&nbsp;&nbsp;Theoretical Philosophy <br> Complutense University of Madrid <br><br> Ciudad Universitaria <br> 28040 Madrid <br> Spain <br><br> Tel.&#58; +34 91 394 6054 <br> Fax.&#58; +34 91 394 5252 <br> email&#58; <a href="mailto:inaki.sanpedro@ucm.es">inaki.sanpedro@ucm.es</a> <br><br>

# logo: isanpedro/arxiu/ventana.jpg
